print('welcome to digital solutions, gabe')

my_name = input('Enter your name: ')
print(type(my_name))
print(len(my_name))
print(my_name.upper())
print(my_name.capitalize())
print(my_name.lower())
print(my_name[0])
print(my_name[1])
print(my_name[-1])
print(my_name[-2])
print(my_name[0:-1])
# print('Welcome', my_name, 'to DIS11')
